---
# control
control:
  data_name: AmazonBeauty
  model_name: simplex
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
resume_mode: 0
profile: False
